### ISSUE TITLE
Old Power BI Desktop on VM images

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#117]
This relates to issue #62 . Although PBI Desktop was updated on the VM in February 2021 to the November 2020 release, the current release is now April 2021. So the same supportability considerations apply again.

The same also applies to the Paginated Report Builder, though the Paginated Reports technology is changing less frequently, so the impact of changes there would likely be less material.

Can some kind of a periodic and more frequent update process please be worked out for the VM image?

**Comment by shannonlindsay** [comment]
Hi Vitaly - thanks for raising this. We are aware that it is an issue and are discussing how we can rectify this. I'm going to close this issue because it is noted and under consideration, not because it is fixed. With the next course update the software will be updated, and we'll look into increasing the frequency. I will post the solution in the MCT courseware forum (as far as frequency goes).
