### ISSUE TITLE
Targets empty if filter is not applied

### ISSUE THREAD

**Issue by madiepev** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#120]
#### Step: 08

Description of issue
When adding targets to the clustered bar chart, targets don't appear. This is because we didn't filter on one specific Salesperson from the Salesperson(Performance) table. In the solution file for this lab it seems a filter on page is added for this reason. This should also be included in instructions here. Or it should be noted that Targets will be empty because of this to avoid confusion.

**Comment by VitalyMCT** [comment]
+1 

My students just ran across the same issue.

**Comment by boomalator** [comment]
Indeed, just found this in class today as well.
This is the same as #121, I believe.

**Comment by datarelish** [comment]
Yes, this issue is still happening. The purpose is that the Power Bi report is simulating the row-level security filters during report design and testing, so the users are supposed to pick 'Michael Blythe' from Salesperson and add it to the 'Filters on this page' option in the Filters pane. However, the step is missing. It needs to be included for the relationships to work in the data model.
It is *incredibly* confusing for trainees.  Can this be added in? I can see that some training consultancies have updated their material so it is achievable. For example, [Peter Lo's link, page 12](http://www.peter-lo.com/Teaching/AMA-BI/Exercise1.pdf).

**Comment by shannonlindsay** [comment]
Thanks all for this feedback. The instructions have been updated to include filtering the page on Michael Blythe. Note that in the next iteration of the course, which will be released in June (exact date TBD), we will be adding the RLS content back to the course to accompany Module 13.
