### ISSUE TITLE
Lab 12A Cannot Add User From Alternate Domain

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#39]
# Module: 12A
Exercise 1: Configure Dataset Security
Task 1: Configure dataset security
Step 3: In the Members box, commence typing the account name of your classroom partner—when it is listed, select it.

Description of issue:  Lab instructions advise the user to leverage their partner's account.  In the instance of provided tenants, they are from alternate domains and the user is not allowed to add a user from an outside organization.  Suggestion, would be to add steps to provision a user under the the same organization and leverage that account as the "partner" account or remove these **classroom partner** references (starting in module 10).

**Comment by VitalyMCT** [comment]
Yes, I've just finished teaching a class and this was one of the things that required some workarounds. 

I provisioned all students on my personal tenant. This was they were able to complete all the partner-related exercises. 

Using student-specific ALH-assigned tenants or having students create independent O365 tenants would be a blocker for completing partner-related exercises.

**Comment by mreherefortea** [comment]
Hello Team:

While this is being addressed, could something be implemented by the labhosters?  For example, a script could be added that creates the user accounts against the provided tenant domain.  Thank you for your time.

**Comment by Derekp20** [comment]
I have written instructions for delegates to use the AAD Admin feature (from the App Launcher icon in the PowerBI Service), to create a new user called Pamela Ansman-Wolfe with an email address of pamela-ansman-wolfe@..., and granted an Office 365 licence. They can use an incognito window to connect to PowerBI with a different account.

Yes automation of this with a built in script would be better.

**Comment by mreherefortea** [comment]
Hello Team:

Revisiting this issue. Is there an ETA of getting this resolved in the instructions?  Instructors have been custom authoring their own instructions but I wanted to follow up and see if there is an ETA of having an official instructional update to resolve this please? Thank you for your time.

**Comment by luconsta** [comment]
Well, after they "teasing" with Row Level Security from the LAB01, LAB02 (that will be "reinforced" in LAB 03), then in LAB03 mentioning that RLS will show again in LAB05, and in LAB04 will mention "will see RLS in the next lab".... they forgot to mention that RLS will be presented as information muuuuuuch later, in MODULE 13 (the last one) and the "key component" for the "partner account" will be in a previous lab: LAB10.... :))

So, the "**_PartnerAccount_**" is introduced in lab [da-100-10a_instructions.md](https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/blob/master/Instructions/Labs/da-100-10a_instructions.md) on **Exercise 2: Refresh the Dataset, Task 1: Update the lab database, Step 2&3** that mentioning:

2. Inside the **D:\DA100\Setup folder**, right-click the **UpdateDatabase-3-AddPartnerAccount.ps1** file, and then select **Run with PowerShell**.
3. **When prompted, enter the account name of your classroom partner**, and then press **Enter**.

So, as @Derekp20 mentioned, you could prepare from the LAB01 an Office365 user, and does not matter the name and/or address used, just make sure when running the above script to use the proper address on the same domain you prepared for the rest of the labs.
When running that script, it will update the **DimEmployee** table and set for the **[EmployeeKey] = 286** the email address you provided, so **_Pamela Ansam-Wolfe_** will have that email address.

Otherwise, as @VitalyMCT mentioned, you should prepare on the trainer account all the users, but this will interfere with other labs where some other scripts should be executed.

HTH

**Comment by shannonlindsay** [comment]
Hi all. This has been sorted as lab 12A is no longer part of the course. Publishing and sharing Power BI content has been moved to an instructor demo per the Feb 21 course update. Thanks for the discussion!
