### ISSUE TITLE
All Files Solution content

### ISSUE THREAD

**Issue by swptmp** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#43]
# Module: 09A
#### Step: 01

Description of issue
Student is trying to open the Module 09A solution and is complaining that there is an Unable to connect error, stating that the dataset is not accessible.  Are the solutions supposed to be populated for a student to be able to jump in anywhere in the labs, or is it necessary for them to complete all tasks?  There are some functioning solutions, for example Lab06B which contains an Assets folder.
Repro steps:

1. Open starter or solution in provided 
1.Receive error 
1.
![image](https://user-images.githubusercontent.com/37548845/98242207-64065e00-1f6c-11eb-8f77-7e3978cec734.png)

**Comment by VitalyMCT** [comment]
The reason for this error is that the report is connected to a dataset in Live mode to a tenant to which the students do not have access to (i.e. original tenant the course author used to save the file).

The fix is to click Edit and reconnect to the student's own dataset (published in 6B, etc.) This is a common issue and the instructions need to be amended to walk students through the process.

**Comment by swptmp** [comment]
Thanks so much. That did the trick.  I have updated our content to add the fix.
