### ISSUE TITLE
how do i create database of AdventureWorksDW2020 

### ISSUE THREAD

**Issue by rainpgy1** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#50]
# Module: 00
#### Step: 00

Description of issue
i can't get those table from that database. i can't setup database
how do i get those tables?
Repro steps:

1.
1.
1.

**Comment by Derekp20** [comment]
If you are an MCT you have free access to the lab providers that include a SQL Database in the VM. Or you can download  the original AdventureworksDW database from github https://github.com/Microsoft/sql-server-samples/releases/tag/adventureworks

**Comment by Derekp20** [comment]
Or from the Lab files https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/tree/master/Allfiles

**Comment by luconsta** [comment]
I think the real problem here is missing steps and/or missing setup requirements for restoring/accessing the database from the .**AdventureWorksDW2020.bak** file provided in **DatabaseBackup** folder.

Using a "local" SQL Server should provide the required steps to download [SQL Server Express](https://www.microsoft.com/en-us/sql-server/sql-server-downloads) and a script or steps to restore the database from the backup provided. 

The former MOC-20778 had scripts for restoring DB and detailed steps how to do it. Moreover the same "old 20778" had a Word document  with steps on how to create an Azure SQL Database by restoring a sample database (**_AdventureWorksLT_** which probably is different from this new **_AdventureWorksDW2020_**).

Eventually, to use the Azure SQL  instead a local SQL server, a BACPAC file should be provided instead of the BAK file and the required steps to  create the database from that BACPAC file. But this is a complex task and I'm not sure if the provided PowerShell scripts will work in this case.

**Comment by shannonlindsay** [comment]
@rainpgy1 - can you confirm that you are now able to access the AdventureWorksDW2020 using the .bac file located in Allfiles/DA-100-Allfiles/DatabaseBackup/?

**Comment by shannonlindsay** [comment]
All files are now available here: https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/tree/master/Allfiles/DA-100-Allfiles
