### ISSUE TITLE
Orders, Titles, Numbers

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI#75]
# Module: ALL

Slides and Student book and Labs do not match in order, nor numbering.

Repro steps:

1. Look at powerpoint
1. Look at student guide in skillpipe
1. Look at lab instructions on GitHub or a lab provider.

Why would you "recommend" doing Perform Data Analysis in Power BI Desktop before Create a Power BI Paginated Report in the Lab instructions, but list them as the opposite order in the slides and student manual?

Why would it make sense to anyone to have to tell students that  "We are doing lab 11 for module 9" and "lab 9 for module 8".

This is needless confusion for students and extra classroom management for no benefit.

**Comment by shannonlindsay** [comment]
Hi @boomalator - thanks for your feedback. The name of the labs are now the same as the name of the module. For example, Module 9 in SkillPipe "Create Paginated Reports in Power BI" goes along with lab 11 "Create a Power BI Paginated Report."

This was our most recent attempt to make the numbering less confusing. This process is iterative and we will consider it for a future update.

**Comment by boomalator** [comment]
I'm sorry, but this is a "fail" -- I can't fathom any logical reason where this would possibly make sense.

![image](https://user-images.githubusercontent.com/17992669/111693860-c6168000-87f6-11eb-84e9-a694e973500a.png)

**Comment by shannonlindsay** [comment]
Thanks for the screenshot @boomalator, I was understanding the issue differently. Is the screenshot from a Lab on Demand environment? Or who is the lab hoster?

**Comment by shannonlindsay** [comment]
Ah - great catch on the different order in the Allfiles @jbeidleman - thank you! That is an easy fix. The overall order is a large issue that we'll take under consideration for our next update. Thanks to you both. I'll update and close the issue once this is done.

**Comment by boomalator** [comment]
Well, the fact that there isn't a lab for each module is kinda odd, and whether it's best to skip a number somewhere or have two different number sequences could be debated, but the order, at the very least, should match. Don't forget that the order is repeated at the top of each set of lab instructions, and the pages of the lab themselves --- and then there's the student book (and instructor guide), and the slides.... a lot of mismatches.

**Comment by luconsta** [comment]
Well, lab numbering on this course was a pain from the very beginning, and I thought after an major update, will came a major improvement but it seems to be worst that the previous release. :(

I don't now why Microsoft did not respect the "good old method", from years ago, when there was a strict relation between "**module number**" and "**lab number**" - what could be more easy than have the **same number**?
And if an module have more labs were just added a letter: A, B, C.

Now, because of a "full name convention" correlated with some numbering, is even harder to find the proper lab.

Just a simple example, after the February 26, 2021 update, the power point slides downloaded from https://learningdownloadcenter.microsoft.com/ have a weird name folder "DA-100T00A-ENU-PowerPoint_Jan Updates" (I thought is a "February update" not January) so causing another confusion.... but let's get back to the Module/Lab Numbering:

Module 5 (I know it has 2 labs ;-) ) - DA-100 Mod5-ENU-PowerPoint.pptx
Slide 15 - Lab: Introduction to DAX in Power BI Desktop
Slide 21 - Lab: Advanced DAX in Power BI Desktop

If you look into https://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI/tree/master/Instructions/Labs you **will NOT find the labs neither by number, neither by name**.

If the Labs were numbered as "in older times" it were very simple:
**LAB05A**-With whatsoever name
**LAB05B**-With whatsoever other name

No matter the name you would like to give them could be easily mapped by these method to the Module and position in module, and the "sort order" will be "natural" in any file system.

And again I have to keep at hand a "stellar map" to find the proper correlation between modules and labs because on **Module 9** the lab is "**Creating a Paginated Report**" and guess what - in the lab order is "**11-create-power-bi-paginated-report.md**"... nice! Why could not be LAB09A-Creating a Paginated Report (being a single lab and to respect the "code size" for the modules with more labs, just add an "A").

The first version of the class has this kind of numbering but wasn't used properly and caused more problems... maybe the third version will set this properly. ;-)

**Comment by shannonlindsay** [comment]
With the March 2021 course update we made an effort to standardize naming, orders, and titles. We have also added a GitHub page for this course that you can use and/or share with learners to help map the modules to the labs.  https://microsoftlearning.github.io/DA-100-Analyzing-Data-with-Power-BI/
